/*
 * Sonar Cryptography Plugin
 * Copyright (C) 2024 PQCA
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to you under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.ibm.plugin.translation.translator.contexts;

import com.ibm.engine.model.Algorithm;
import com.ibm.engine.model.Curve;
import com.ibm.engine.model.IValue;
import com.ibm.engine.model.KeyAction;
import com.ibm.engine.model.KeySize;
import com.ibm.engine.model.SaltSize;
import com.ibm.engine.model.ValueAction;
import com.ibm.engine.model.context.DetectionContext;
import com.ibm.engine.model.context.IDetectionContext;
import com.ibm.engine.model.context.PrivateKeyContext;
import com.ibm.engine.model.context.PublicKeyContext;
import com.ibm.engine.rule.IBundle;
import com.ibm.mapper.IContextTranslation;
import com.ibm.mapper.mapper.openssl.OpenSslKeyMapper;
import com.ibm.mapper.mapper.openssl.OpenSslMacMapper;
import com.ibm.mapper.model.IAlgorithm;
import com.ibm.mapper.model.INode;
import com.ibm.mapper.model.Key;
import com.ibm.mapper.model.KeyLength;
import com.ibm.mapper.model.PrivateKey;
import com.ibm.mapper.model.PublicKey;
import com.ibm.mapper.model.SaltLength;
import com.ibm.mapper.model.SecretKey;
import com.ibm.mapper.model.functionality.Decapsulate;
import com.ibm.mapper.model.functionality.Encapsulate;
import com.ibm.mapper.model.functionality.KeyDerivation;
import com.ibm.mapper.model.functionality.KeyGeneration;
import com.ibm.mapper.utils.DetectionLocation;
import com.sonar.cxx.sslr.api.AstNode;
import java.util.Optional;
import javax.annotation.Nonnull;

/**
 * Translator for C++ key detection contexts.
 *
 * <p>This translator handles the translation of key-related detection values (public keys, private
 * keys, secret keys) to the mapper model nodes.
 */
public final class CxxKeyContextTranslator implements IContextTranslation<AstNode> {

    @Override
    public @Nonnull Optional<INode> translate(
            @Nonnull IBundle bundleIdentifier,
            @Nonnull IValue<AstNode> value,
            @Nonnull IDetectionContext detectionContext,
            @Nonnull DetectionLocation detectionLocation) {
        if (isRawKey(detectionContext)
                && (value instanceof ValueAction<AstNode> || value instanceof Algorithm<AstNode>)) {
            return rawKey(bundleIdentifier, value, detectionContext, detectionLocation);
        }
        final Optional<INode> translated =
                translateValue(bundleIdentifier, value, detectionContext, detectionLocation);
        // the algorithm of a key generated by the detected call (e.g. EVP_PKEY_Q_keygen)
        if (detectionContext.is(PrivateKeyContext.class)) {
            translated
                    .filter(IAlgorithm.class::isInstance)
                    .ifPresent(
                            algorithm ->
                                    algorithm.put(
                                            new KeyGeneration(
                                                    KeyGeneration.Specification.PRIVATE_KEY,
                                                    detectionLocation)));
        }
        return translated;
    }

    /** Whether the value is the type of a key created from raw bytes (see OpenSSLEvpRawKey). */
    private static boolean isRawKey(@Nonnull IDetectionContext detectionContext) {
        return detectionContext instanceof DetectionContext context
                && context.get("kind").filter("RAW_KEY"::equals).isPresent();
    }

    /**
     * A key created from raw bytes: a secret key holding its MAC algorithm, or a private or public
     * key (by the detection context) holding its asymmetric algorithm. The key is imported, not
     * generated.
     */
    @Nonnull
    private Optional<INode> rawKey(
            @Nonnull IBundle bundleIdentifier,
            @Nonnull IValue<AstNode> value,
            @Nonnull IDetectionContext detectionContext,
            @Nonnull DetectionLocation detectionLocation) {
        final Optional<? extends INode> mac =
                new OpenSslMacMapper().parse(value.asString(), detectionLocation);
        if (mac.isPresent() && mac.get() instanceof IAlgorithm macAlgorithm) {
            return Optional.of(new SecretKey(new Key(macAlgorithm)));
        }
        return translateValue(bundleIdentifier, value, detectionContext, detectionLocation)
                .filter(IAlgorithm.class::isInstance)
                .map(
                        algorithm -> {
                            final Key key = new Key((IAlgorithm) algorithm);
                            return detectionContext.is(PublicKeyContext.class)
                                    ? new PublicKey(key)
                                    : new PrivateKey(key);
                        });
    }

    @Nonnull
    private Optional<INode> translateValue(
            @Nonnull IBundle bundleIdentifier,
            @Nonnull IValue<AstNode> value,
            @Nonnull IDetectionContext detectionContext,
            @Nonnull DetectionLocation detectionLocation) {

        // settings made on a key generation context (see OpenSSLEvpKeyGen)
        if (value instanceof KeySize<AstNode> keySize) {
            return Optional.of(new KeyLength(keySize.getValue(), detectionLocation));
        } else if (value instanceof SaltSize<AstNode> saltSize) {
            // a negative salt length selects a length derived from the digest or the key
            return saltSize.getValue() > 0
                    ? Optional.of(new SaltLength(saltSize.getValue(), detectionLocation))
                    : Optional.empty();
        } else if (value instanceof Curve<AstNode> curve) {
            return new OpenSslKeyMapper()
                    .parseCurve(curve.asString(), detectionLocation)
                    .map(node -> node);
        } else if (value instanceof KeyAction<AstNode> keyAction) {
            return switch (keyAction.getAction()) {
                case PRIVATE_KEY_GENERATION ->
                        Optional.of(
                                new KeyGeneration(
                                        KeyGeneration.Specification.PRIVATE_KEY,
                                        detectionLocation));
                case PUBLIC_KEY_GENERATION ->
                        Optional.of(
                                new KeyGeneration(
                                        KeyGeneration.Specification.PUBLIC_KEY, detectionLocation));
                case SECRET_KEY_GENERATION ->
                        Optional.of(
                                new KeyGeneration(
                                        KeyGeneration.Specification.SECRET_KEY, detectionLocation));
                case GENERATION -> Optional.of(new KeyGeneration(detectionLocation));
                // operations performed with a key (see OpenSSLEvpKeyUsage)
                case KDF -> Optional.of(new KeyDerivation(detectionLocation));
                case ENCAPSULATION -> Optional.of(new Encapsulate(detectionLocation));
                case DECAPSULATION -> Optional.of(new Decapsulate(detectionLocation));
            };
        }

        if (value instanceof ValueAction<AstNode> || value instanceof Algorithm<AstNode>) {
            return new OpenSslKeyMapper()
                    .parse(value.asString(), detectionLocation)
                    .map(node -> node);
        }

        return Optional.empty();
    }
}
